[package]
name = "setter"
version = "0.0.0"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
solana-program = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]
