[package]
name = "mutim-cpi"
version = "0.0.0"
license = "Apache-2.0"
edition = "2018" # follows SPL

[dev-dependencies]
borsh = "^0.10"
solana-program = "1.16.0"
solana-program-test = "1.16.0"
solana-sdk = "1.16.0"
tokio = "1.14.0"


[lib]
crate-type = ["cdylib", "lib"]
